# Generated by Django 2.2.6 on 2021-03-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
