# Generated by Django 2.2.6 on 2021-03-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0002_auto_20210320_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time_posted',
        ),
    ]
