# Generated by Django 2.2.6 on 2021-03-20 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0003_remove_comment_time_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
