# Generated by Django 2.2.17 on 2021-03-29 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0008_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(blank=True, upload_to='posts')),
                ('likes', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
