# Generated by Django 2.2.6 on 2021-03-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0008_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
