# Generated by Django 2.2.6 on 2021-03-29 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0011_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meme_portal.UserProfile'),
            preserve_default=False,
        ),
    ]
