# Generated by Django 2.2.17 on 2021-03-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0013_merge_20210329_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
