# Generated by Django 2.2.6 on 2021-03-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0016_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
