# Generated by Django 2.2.6 on 2021-04-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0020_auto_20210331_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='meme_portal.Forum'),
        ),
    ]
