# Generated by Django 2.2.6 on 2021-04-02 22:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0022_auto_20210402_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('name',)),
        ),
    ]
