# Generated by Django 2.2.6 on 2021-04-02 23:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0023_auto_20210402_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True),
        ),
    ]
