# Generated by Django 2.2.6 on 2021-04-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0024_auto_20210402_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='meme_portal.Forum'),
        ),
    ]
