# Generated by Django 2.2.17 on 2021-04-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0027_auto_20210405_1010'),
        ('meme_portal', '0027_auto_20210405_1013'),
    ]

    operations = [
    ]
