# Generated by Django 2.2.6 on 2021-04-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_portal', '0028_merge_20210405_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
